blank_issues_enabled: true
contact_links:
  - name: ğŸ«¶ Support Portal
    about: Get support using through our portal.
    url: https://support.modrinth.com
  - name: ğŸ’¬ èŠå¤©
    about: å‡å¦‚æˆ‘ä»¬çš„DiscordæœåŠ¡å™¨æ¥è®¨è®ºModrinthã€‚
    url: https://discord.modrinth.com
  - name: ğŸ›£ï¸ è·¯çº¿å›¾
    about: æŸ¥çœ‹æˆ‘ä»¬çš„è·¯çº¿å›¾. Please do not open issues for items on our roadmap.
    url: https://roadmap.modrinth.com
  - name: ğŸ“š æ–‡æ¡£
    about: å…³äºModrinth's APIçš„æœ‰ç”¨çš„æ–‡æ¡£
    url: https://docs.modrinth.com